### ISSUE TITLE
msproject in your code

### ISSUE THREAD

**Issue by nooralahzadeh** [Cisco-Talos/fnc-1#2]
Hi ,
It seems that you are using ms project in your code, but there is no any comment how to setup that,
Any possibility to describe it to see how to setup?
Thanks

**Comment by yuxip** [comment]
Hi @nooralahzadeh , I believe AlignmentFeatureGenerator is the only module which includes mscproject and this module is not required anywhere in our code. It was actually a work-in-progress feature that has never been included our final model.

It's been a while so I could be wrong. Let me know if you still have problems.

**Comment by nooralahzadeh** [comment]
Hi, Thanks for the reply, It seems you import it in "xgb_train_cvBodyId.py" but you do not use it in the code.
I will comment it out.

**Comment by yuxip** [comment]
Ah, yes. It should have been removed.
Thank you!

**Comment by nooralahzadeh** [comment]
May I ask you why you have the following weighting:
    w = np.array([1 if y == 3 else 4 for y in cv_y])
I have 3 classes and I wan to use your code, Could you point me where I have to update your code?

**Comment by yuxip** [comment]
It was related to the scoring function of the competition, see the "Evaluation" section of http://www.fakenewschallenge.org/

To modify the number of class, you need to update the training code, e.g. xgb_train.py, specifically look to the num_class in params_xgb and targets in the build_data function.
